---
# .pre-commit-config.yml
# Pre-commit hook tasks.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      # - id: poetry-export
      #   args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
      - id: poetry-export
        language: script
        language_version: null
        entry: scripts/poetry-export.sh
        args: []
