site_name: Buildarr

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Release Notes:
    - Buildarr Docker Container: "release-notes/buildarr-docker.md"
    - Buildarr Core: "release-notes/buildarr.md"
    - Buildarr Sonarr Plugin: "release-notes/buildarr-sonarr.md"
    - Buildarr Prowlarr Plugin: "release-notes/buildarr-prowlarr.md"
  - Installation: "installation.md"
  - Configuration: "configuration.md"
  - Plugins:
    - Introduction: "plugins/index.md"
    - Buildarr Sonarr Plugin:
      - Introduction: "plugins/sonarr/index.md"
      - Release Notes: "plugins/sonarr/release-notes.md"
      - Configuration:
        - Host Configuration: "plugins/sonarr/configuration/host.md"
        - Media Management: "plugins/sonarr/configuration/media-management.md"
        - Profiles:
          - Quality Profiles: "plugins/sonarr/configuration/profiles/quality.md"
          - Language Profiles: "plugins/sonarr/configuration/profiles/language.md"
          - Delay Profiles: "plugins/sonarr/configuration/profiles/delay.md"
          - Release Profiles: "plugins/sonarr/configuration/profiles/release.md"
        - Quality: "plugins/sonarr/configuration/quality.md"
        - Indexers: "plugins/sonarr/configuration/indexers.md"
        - Download Clients: "plugins/sonarr/configuration/download-clients.md"
        - Import Lists: "plugins/sonarr/configuration/import-lists.md"
        - Connect: "plugins/sonarr/configuration/connect.md"
        - Metadata: "plugins/sonarr/configuration/metadata.md"
        - Tags: "plugins/sonarr/configuration/tags.md"
        - General: "plugins/sonarr/configuration/general.md"
        - UI: "plugins/sonarr/configuration/ui.md"
    - Buildarr Prowlarr Plugin:
      - Introduction: "plugins/prowlarr/index.md"
      - Release Notes: "plugins/prowlarr/release-notes.md"
      - Configuration:
        - Host Configuration: "plugins/prowlarr/configuration/host.md"
        - Settings:
          - Indexers:
            - Indexers: "plugins/prowlarr/configuration/settings/indexers/indexers.md"
            - Proxies: "plugins/prowlarr/configuration/settings/indexers/proxies.md"
          - Apps:
            - Applications: "plugins/prowlarr/configuration/settings/apps/applications.md"
            - Sync Profiles: "plugins/prowlarr/configuration/settings/apps/sync-profiles.md"
          - Download Clients: "plugins/prowlarr/configuration/settings/download-clients.md"
          - Notifications: "plugins/prowlarr/configuration/settings/notifications.md"
          - Tags: "plugins/prowlarr/configuration/settings/tags.md"
          - General: "plugins/prowlarr/configuration/settings/general.md"
          - UI: "plugins/prowlarr/configuration/settings/ui.md"
  - Usage: "usage.md"
  - GitHub: "https://github.com/buildarr/buildarr"
  # TODO: Development documentation.
  # - Development:
  #   - Introduction: "development/index.md"
  #   - Plugins: "development/plugins.md"

watch:
  - docs
  - externals
