name: build

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - pre-commit
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build-mkdocs:
    name: Test MkDocs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build docs using MkDocs
        uses: Tiryoh/actions-mkdocs@v0
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: buildarr-docs
          path: site
          retention-days: 5
