name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    needs: build
