name: mkdocs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          requirements: "requirements.txt"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          external_repository: buildarr/buildarr.github.io
          publish_branch: main
