name: mkdocs

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          requirements: "requirements.txt"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site
          external_repository: buildarr/buildarr.github.io
          publish_branch: main
