name: pre-commit

on:
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - uses: pre-commit/action@v3.0.0
