name: Pre-commit hooks

on:
  workflow_dispatch:
  workflow_run:

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0
