name: Publish

on:
  workflow_call:

jobs:
  publish-githubpages:
    name: GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - name: Download Buildarr Docs from build artifacts
        uses: actions/download-artifact@v3
        with:
          name: buildarr-docs
          path: site
      - name: Publish docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          repository-name: buildarr/buildarr.github.io
          branch: main
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          clean: true
