name: Publish

on:
  workflow_call:

jobs:
  publish-buildarr-github-io:
    name: buildarr.github.io
    environment:
      name: buildarr.github.io
      url: https://buildarr.github.io
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download docs from build artifacts
        uses: actions/download-artifact@v3
        with:
          name: buildarr-docs
          path: site
      - name: Publish docs to buildarr.github.io
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          repository-name: ${{ vars.DEPLOY_REPOSITORY }}
          branch: ${{ vars.DEPLOY_BRANCH }}
          ssh-key: |
            ${{ secrets.DEPLOY_KEY }}
          clean: true
