name: Pull Request

on:
  pull_request:

jobs:
  pre-commit:
    name: Pre-commit
    uses: ./.github/workflows/pre-commit.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: pre-commit
